"""empty message

Revision ID: cd7c46d5e818
Revises: 2ce46f317709
Create Date: 2018-12-18 02:29:57.272030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd7c46d5e818'
down_revision = '2ce46f317709'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isok', sa.Boolean(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('input_description', sa.Text(), nullable=True),
    sa.Column('output_description', sa.Text(), nullable=True),
    sa.Column('input_sample', sa.Text(), nullable=True),
    sa.Column('output_sample', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('problems')
    # ### end Alembic commands ###
